### ISSUE TITLE
Improving performances

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/libs#10]
Since #7, we use `Flux` (~ `Deno.reader & Deno.seeker`) to navigate through parsed stream/string.

Unfortunately there are some performance issues, which could maybe be improved by using some sort of cache.

|input|v1|v2|v2 + progress logged in stdout|
|-|-|-|-|
|`string`|~7s/mb|~12s/mb|~18s/mb|
|`stream`|N/A|~42s/mb|~53s/mb|

**Comment by phil294** [comment]
I am running some kind of batch script and for ~1000 parse iterations, this library took 2.8s while both https://deno.land/x/ts_xml_parser@1.0.0 and https://deno.land/x/xml2js@1.0.0 were at around .2s, so around 10 times faster. Hope this helps. I like this library though, thanks for your work.
