### ISSUE TITLE
No option to force disable any XML escaping during stringify

### ISSUE THREAD

**Issue by YunHsiao** [lowlighter/libs#33]
![image](https://github.com/lowlighter/xml/assets/9102404/09cfaa4b-dc48-4a91-b572-dabac3545ddc)
I don't think there's any way to customize this property, please add a switch for this to stringify options. For now we have to unescape everything in the replacer which is not ideal.

**Comment by lowlighter** [comment]
Hi !
The stringifier should now only escape entities when needed (i.e. it'll still escape `<`/`>` in nodes and `"`/`'` in attributes for example)

Let me know if it matches what you expected

**Comment by YunHsiao** [comment]
Thanks! It works for me.
