### ISSUE TITLE
`otpsecret` from `totp` to support customized size

### ISSUE THREAD

**Issue by imcotton** [lowlighter/libs#75]
e.g.

```ts
export function otpsecret(n = 20): string { 
  return encodeBase32(crypto.getRandomValues(new Uint8Array(n))).replaceAll("=", "") 
} 
```
This is backwards compatible addition, any thoughts?

**Comment by lowlighter** [comment]
Yes I don't think there's any restriction about the secret length according to: https://github.com/google/google-authenticator/wiki/Key-Uri-Format#secret so we could allow a customized size
