### ISSUE TITLE
@libs/xml produces invalid output when ampersands are used in "#text"

### ISSUE THREAD

**Issue by sophietelle** [lowlighter/libs#82]
https://www.w3.org/TR/xml/ 2.4 Character Data and Markup
> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a [comment](https://www.w3.org/TR/xml/#dt-comment), a [processing instruction](https://www.w3.org/TR/xml/#dt-pi), or a [CDATA section](https://www.w3.org/TR/xml/#dt-cdsection). If they are needed elsewhere, they MUST be [escaped](https://www.w3.org/TR/xml/#dt-escape) using either [numeric character references](https://www.w3.org/TR/xml/#dt-charref) or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and MUST, [for compatibility](https://www.w3.org/TR/xml/#dt-compat), be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a [CDATA section](https://www.w3.org/TR/xml/#dt-cdsection).

## Reproduction
```js
import * as xml from "@libs/xml";

let obj = {
  "@version": "1.0",
  "@encoding": "utf-8",
  "resources": {
    "string": [
      {
        "@name": "strings",
        "#text": "Passport & Email",
      }
    ]
  },
};

console.log(xml.stringify(obj))
/* output:
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="strings">Passport & Email</string>
</resources>
*/
```

**Comment by lowlighter** [comment]
Thanks for reporting, this should be fixed now
