### ISSUE TITLE
Reviving hex character entities is broken, as it matches only digits, not letters.

### ISSUE THREAD

**Issue by qbeuek** [lowlighter/libs#87]
https://github.com/lowlighter/libs/blob/ad75220ef31d14ac8d2f8bca2ca8a28be0f79e02/xml/parse.ts#L425

If the input xml contains hex encoded character literals like `&#xa;` the current regular expression will not match it as it expects only digits `\d+`, not hex letters.

**Comment by lowlighter** [comment]
Hi ! 
Thanks for the report, the newest version published should handle all characters from hexadecimal coded now, good catch !
